#!/usr/bin/env python3
"""
Generate Home Assistant and AppDaemon config files from config.yaml.

Usage:
    python deploy.py

Output:
    ha/appdaemon/apps/apps.yaml   — AppDaemon app config
    ha/packages/marstek.yaml      — HA Modbus + template sensors

Copy the entire ha/ directory structure to /config/ on your HA instance.
Supports 1, 2, or 3 batteries (any number >= 1).
"""

import sys
from pathlib import Path
import yaml

ROOT = Path(__file__).parent
CONFIG_FILE = ROOT / "config.yaml"
APPDAEMON_OUT = ROOT / "ha" / "apps.yaml"
HA_OUT = ROOT / "ha" / "packages" / "marstek.yaml"


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------

def load_config() -> dict:
    with open(CONFIG_FILE) as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# AppDaemon config generator
# ---------------------------------------------------------------------------

def build_appdaemon_config(cfg: dict) -> str:
    bats = cfg["batteries"]
    shelly = cfg["shelly"]
    ctrl = cfg["controller"]
    testing = cfg.get("testing", {})

    if testing:
        print("  [testing mode] SoC entities overridden from testing section")

    batteries_ad = []
    for i, bat in enumerate(bats):
        bid = bat["id"]
        # Allow per-battery SoC override in the testing section
        soc = testing.get(f"battery_{i + 1}_soc_entity", f"sensor.{bid}_soc")
        batteries_ad.append({
            "hub":        bid,
            "soc_entity": soc,
            "slave":      bat.get("slave", 1),
        })

    doc = {
        "battery_controller": {
            "module": "battery_controller",
            "class": "BatteryController",
            "grid_power_entity": shelly["entity_id"],
            "grid_power_sign": shelly.get("power_sign", 1),
            "batteries": batteries_ad,
            "poll_interval": ctrl.get("poll_interval", 1),
            "deadband_w": ctrl.get("deadband_w", 50),
            "min_soc": ctrl.get("min_soc", 15),
            "max_soc": ctrl.get("max_soc", 95),
            "watchdog_cycles": ctrl.get("watchdog_cycles", 10),
            "remote_control_interval": ctrl.get("remote_control_interval", 300),
        }
    }
    header = "# Auto-generated by deploy.py - edit config.yaml instead.\n\n"
    return header + yaml.dump(doc, default_flow_style=False, sort_keys=False)


# ---------------------------------------------------------------------------
# HA marstek.yaml generator
# ---------------------------------------------------------------------------

def _sensors_for_battery(bat: dict, scan_interval: int = 5) -> list:
    bid = bat["id"]
    name = bat["name"]
    slave = bat.get("slave", 1)

    def s(sensor_name, unique_suffix, address, data_type, scale, unit,
          device_class=None, state_class=None, count=None):
        entry = {
            "name": f"{name} {sensor_name}",
            "unique_id": f"{bid}_{unique_suffix}",
            "slave": slave,
            "address": address,
            "input_type": "holding",
            "data_type": data_type,
            "scale": scale,
            "scan_interval": scan_interval,
            "unit_of_measurement": unit,
        }
        if count:
            entry["count"] = count
        if device_class:
            entry["device_class"] = device_class
        if state_class:
            entry["state_class"] = state_class
        return entry

    return [
        s("SoC",                      "soc",                      32104, "uint16", 1,    "%",   "battery",     "measurement"),
        s("Battery Power",            "battery_power",            32102, "int32",  1,    "W",   "power",       "measurement", count=2),
        s("AC Power",                 "ac_power",                 32202, "int32",  1,    "W",   "power",       "measurement", count=2),
        s("AC Voltage",               "ac_voltage",               32200, "uint16", 0.1,  "V",   "voltage",     "measurement"),
        s("Internal Temperature",     "temperature",              35000, "int16",  0.1,  "°C",  "temperature", "measurement"),
        s("Inverter State",           "inverter_state",           35100, "uint16", 1,    "",    None,          None),
        s("Total Charging Energy",    "total_charging_energy",    33000, "uint32", 0.01, "kWh", "energy",      "total_increasing", count=2),
        s("Total Discharging Energy", "total_discharging_energy", 33002, "int32",  0.01, "kWh", "energy",      "total_increasing", count=2),
    ]


def _template_sensors(bats: list) -> list:
    """Build HA template sensor definitions for N batteries."""
    sensors = []

    # Per-battery state label
    for bat in bats:
        bid = bat["id"]
        name = bat["name"]
        sensors.append({
            "name": f"{name} State",
            "unique_id": f"{bid}_state_text",
            "state": (
                "{%- set s = states('sensor." + bid + "_inverter_state') | int(-1) -%}\n"
                "{%- set map = {0:'Sleep',1:'Standby',2:'Charging',3:'Discharging',"
                "4:'Backup',5:'OTA Upgrade',6:'Bypass'} -%}\n"
                "{{ map.get(s, 'Unknown') }}"
            ),
        })

    # Combined SoC — average of all batteries
    soc_vars = "\n".join(
        f"{{%- set s{i+1} = states('sensor.{bat['id']}_soc') | float(0) -%}}"
        for i, bat in enumerate(bats)
    )
    soc_sum  = " + ".join(f"s{i+1}" for i in range(len(bats)))
    sensors.append({
        "name": "Batteries Combined SoC",
        "unique_id": "batteries_combined_soc",
        "unit_of_measurement": "%",
        "state": f"{soc_vars}\n{{{{ (({soc_sum}) / {len(bats)}) | round(1) }}}}",
    })

    # Combined power — sum of all batteries
    pwr_vars = "\n".join(
        f"{{%- set p{i+1} = states('sensor.{bat['id']}_battery_power') | float(0) -%}}"
        for i, bat in enumerate(bats)
    )
    pwr_sum = " + ".join(f"p{i+1}" for i in range(len(bats)))
    sensors.append({
        "name": "Batteries Combined Power",
        "unique_id": "batteries_combined_power",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state": f"{pwr_vars}\n{{{{ ({pwr_sum}) | round(0) }}}}",
    })

    return sensors


def build_ha_config(cfg: dict) -> str:
    bats = cfg["batteries"]
    scan_interval = cfg.get("controller", {}).get("modbus_scan_interval", 5)

    modbus = [
        {
            "name": bat["id"],
            "type": "tcp",
            "host": bat["ip"],
            "port": bat.get("port", 502),
            "delay": 3,
            "timeout": 5,
            "sensors": _sensors_for_battery(bat, scan_interval),
        }
        for bat in bats
    ]

    template = [{"sensor": _template_sensors(bats)}]
    doc = {"modbus": modbus, "template": template}

    header = (
        "# Auto-generated by deploy.py - edit config.yaml instead.\n"
        "# Register map: Marstek Venus E v1/v2 firmware.\n\n"
    )
    return header + yaml.dump(doc, default_flow_style=False, sort_keys=False,
                              allow_unicode=True)


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------

def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote  {path.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if not CONFIG_FILE.exists():
        print(f"ERROR: {CONFIG_FILE} not found", file=sys.stderr)
        sys.exit(1)

    cfg = load_config()
    bats = cfg.get("batteries", [])

    if len(bats) < 1:
        print("ERROR: config.yaml must have at least 1 battery", file=sys.stderr)
        sys.exit(1)

    print(f"Loaded config: {', '.join(b['name'] for b in bats)}")

    write(APPDAEMON_OUT, build_appdaemon_config(cfg))
    write(HA_OUT, build_ha_config(cfg))

    print("\nDone. Copy files to Home Assistant:")
    print("  controller/battery_controller.py  ->  /addon_configs/a0d7b954_appdaemon/apps/  (via Terminal)")
    print("  ha/apps.yaml                      ->  /addon_configs/a0d7b954_appdaemon/apps/  (via Terminal)")
    print("  ha/appdaemon.yaml                 ->  /config/appdaemon.yaml                   (via File Editor)")
    print("  ha/packages/                      ->  /config/packages/                         (via File Editor)")


if __name__ == "__main__":
    main()
